export const copy = {
  site: {
    title: 'Carta de Adeus',
    description: 'Escreva sua carta de adeus e deixe sua mensagem ecoar pelo mundo.',
    subtitle: 'Fresno',
  },
  hero: {
    quote: '"Pra cada vez que eu precisei de palavras e não as pude encontrar, eu fiz uma carta. Todas elas são de adeus."',
    cta: 'Escreva sua carta',
    albumInfo: 'Fresno • Novo Álbum',
  },
  form: {
    placeholder: 'Escreva sua carta de adeus...',
    charLimit: '280 caracteres',
    anonymousLabel: 'Enviar anonimamente',
    locationLabel: 'De onde você está escrevendo?',
    locationPlaceholder: 'Buscar cidade...',
    submitButton: 'Enviar carta',
    submitting: 'Enviando...',
  },
  globe: {
    title: 'Cartas pelo mundo',
    loading: 'Carregando cartas...',
    emptyState: 'Seja o primeiro a enviar uma carta.',
  },
  share: {
    title: 'Compartilhar sua carta',
    downloadButton: 'Baixar imagem',
    shareX: 'Compartilhar no X',
    close: 'Fechar',
  },
  success: {
    title: 'Carta enviada!',
    message: 'Sua carta agora está viajando pelo mundo.',
  },
  social: {
    hashtag: '#CartaDeAdeus',
    fresnoHandle: '@fresnorock',
    lucasHandle: '@lucasfresno',
  },
  marquee: {
    title: 'Cartas ao vento',
    subtitle: 'Palavras que ecoam pelo mundo',
    emptyState: 'As primeiras cartas estão a caminho...',
    anonymous: 'Anônimo',
    from: 'de',
  },
  countdown: {
    date: '18 de Abril de 2026',
    tagline: 'A contagem começou.',
    subtitle: 'Carta de Adeus ao vivo. Pela primeira vez.',
    shareButton: 'Compartilhar a espera',
    units: {
      days: 'dias',
      hours: 'horas',
      minutes: 'min',
      seconds: 'seg',
    },
    tweet: {
      template: 'Faltam {days} dias, {hours} horas e {minutes} minutos para @fresnorock ao vivo 🎸\n\nA contagem começou. #CartaDeAdeus\n\ncartadeadeus.cc',
      templateShort: 'Faltam apenas {hours} horas e {minutes} minutos para @fresnorock ao vivo 🎸\n\nHoje é o dia. #CartaDeAdeus\n\ncartadeadeus.cc',
    },
    expired: 'O momento chegou.',
  },
  admin: {
    title: 'Painel Admin',
    login: {
      title: 'Acesso Admin',
      subtitle: 'Entre com seu email autorizado',
      emailPlaceholder: 'seu@email.com',
      submitButton: 'Enviar link de acesso',
      sending: 'Enviando...',
      success: 'Link enviado! Verifique seu email.',
      error: 'Email não autorizado',
      invalidEmail: 'Email inválido',
    },
    nav: {
      dashboard: 'Dashboard',
      letters: 'Cartas',
      logout: 'Sair',
    },
    dashboard: {
      title: 'Visão Geral',
      stats: {
        total: 'Total de cartas',
        pending: 'Aguardando revisão',
        flagged: 'Sinalizadas',
        approved: 'Aprovadas',
        rejected: 'Rejeitadas',
      },
    },
    letters: {
      title: 'Gerenciar Cartas',
      filters: {
        all: 'Todas',
        pending: 'Pendentes',
        flagged: 'Sinalizadas',
        approved: 'Aprovadas',
        rejected: 'Rejeitadas',
      },
      table: {
        content: 'Conteúdo',
        author: 'Autor',
        city: 'Cidade',
        status: 'Status',
        date: 'Data',
        actions: 'Ações',
      },
      actions: {
        approve: 'Aprovar',
        reject: 'Rejeitar',
        share: 'Compartilhar',
      },
      bulkActions: {
        approveSelected: 'Aprovar selecionadas',
        rejectSelected: 'Rejeitar selecionadas',
      },
      emptyState: 'Nenhuma carta encontrada',
      flagReason: 'Motivo da sinalização',
    },
    share: {
      title: 'Compartilhar Carta',
      downloadStory: 'Download Story (1080x1920)',
      downloadOG: 'Download OG (1200x630)',
      downloading: 'Gerando imagem...',
    },
  },
} as const;
